SCAN_FROM = "2024-05-01 00:00"
SCAN_TO = "2024-05-04 00:00"
INTERVAL = "1d"
Symbol_scan = []
VOLATILITY_THRESHOLD = 0.0
PCT_CHANGE_THRESHOLD = 0.2
MIN_VOLUME = 50000
FILTER_MODE = "AND"
symbol = "BTCUSDT"
interval = "1h"
start_time_str = "2024-05-01 01:00"
end_time_str = "2024-05-03 05:00"
INDICATOR_CONDITIONS = {"rsi": {'oversold': 30, 'overbought': 70}, "macd": {'signal_diff_min': 0.0}}
SL_MULTIPLIER = 1.5
RR_RATIO = 2.0
ACTIVE_STRATEGIES = ['strategy_rsi_macd', 'strategy_bollinger_macd', 'strategy_breakout_volume', 'strategy_breakout', 'strategy_candlestick', 'strategy_supertrend_macd', 'strategy_vwap_bounce']
STRATEGY_THRESHOLDS = {"strategy_rsi_macd": 1, "strategy_bollinger_macd": 1, "strategy_breakout_volume": 1, "strategy_breakout": 1, "strategy_candlestick": 1, "strategy_supertrend_macd": 1, "strategy_vwap_bounce": 1}
STRATEGY_MAX_VALUES = {"strategy_rsi_macd": 2, "strategy_bollinger_macd": 2, "strategy_breakout_volume": 3, "strategy_breakout": 2, "strategy_candlestick": 1, "strategy_supertrend_macd": 2, "strategy_vwap_bounce": 2}
